### PR TITLE
Fix reference from iteritems() to items() in Pyramid and bump version.

### PR DESCRIPTION
**Pull request by farvour**
I believe in Python 3, they removed .iteritems() from dict.  This should work in Py2 and Py3 now.

### CODE REVIEW

**Comment by tisdall** [comment]
:+1: I'd like to have py3 support out of the box.

**Comment by maisano** [comment]
sorry for the delay--i've been on holiday.

but thank you, this is great. would you like to add yourself to the contributors section of `README.md` or shall i just go ahead and merge?

**Comment by farvour** [comment]
You can just go ahead and merge it.  :)  Thanks!!

**Comment by tisdall** [comment]
@maisano - don't publish right away to pypi...  there are still some bugs with py3.  I'm working on them right now.

**Comment by tisdall** [comment]
...  please merge though...  I'll put my fixes on top of these.

**Comment by maisano** [comment]
good deal. thanks!

**Comment by maisano** [comment]
whoops. clunky ios...

**Pull request merged**
